FROM python:3.11-slim as builder

ARG APP_ENV
ENV APP_ENV=$APP_ENV
RUN apt-get update && apt-get install -y libgl1-mesa-glx
# RUN apt-get update && apt-get install -y nginx
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /.cache/

WORKDIR /app

COPY . .
RUN pip install -r requirements_ui.txt

EXPOSE 8501
ENTRYPOINT ["sh", "run_ui.sh"]